export const direct = [
  { text: "what's 18 times 6?", answer: 108 },
  { text: "what's 144 divided by 12?", answer: 12 },
  { text: "what's 25 percent of 80?", answer: 20 },
  { text: "what's 17 plus 38?", answer: 55 },
  { text: "what's 9 times 9?", answer: 81 },
  { text: "what's 75 minus 48?", answer: 27 },
  { text: "what's 13 times 7?", answer: 91 },
  { text: "what's 200 divided by 8?", answer: 25 },
  { text: "what's 15 percent of 60?", answer: 9 },
  { text: "what's 6 times 8, minus 12?", answer: 36 },
  { text: "what's 33 plus 47?", answer: 80 },
  { text: "what's 50 percent of 136?", answer: 68 },
  { text: "what's 11 times 12?", answer: 132 },
  { text: "what's 96 divided by 6?", answer: 16 },
  { text: "what's 7 times 8, plus 14?", answer: 70 },
]

export const situational = [
  { text: "you and 4 friends ordered 3 pizzas at 480 each. two of your friends added toppings at 60 each. split equally across all 5 people, how much do you owe?", answer: 312 },
  { text: "you're buying supplies for a party. plates cost 4 dollars for a pack of 10, and you need 60 plates. cups cost 3 dollars for a pack of 8, and you need 40 cups. how much do you spend in total?", answer: 39 },
  { text: "a movie ticket costs 12 dollars. you buy 3 tickets and use a coupon for 15 dollars off. how much do you pay?", answer: 21 },
  { text: "you run a lemonade stand. each cup sells for 2 dollars. today you sold 34 cups but spilled 4 and had to give refunds. how much did you make?", answer: 60 },
  { text: "your phone plan is 80 dollars a month. you and 3 friends split it equally. after 6 months, how much have you personally paid?", answer: 120 },
  { text: "you're at a restaurant. the bill is 45 dollars. you tip 20 percent. what's the total?", answer: 54 },
  { text: "you buy 3 coffees at 4 dollars each and a sandwich at 8 dollars. you pay with a 25-dollar bill. how much change do you get?", answer: 5 },
  { text: "a store has a buy-2-get-1-free sale. shirts cost 25 dollars each. you buy 6 shirts. how much do you pay?", answer: 100 },
  { text: "you earn 14 dollars per hour. you worked 6 hours on saturday and 4 hours on sunday. after paying 30 dollars for transport, how much did you keep?", answer: 110 },
  { text: "you're splitting a hotel room for 2 nights. the room costs 180 dollars per night. you split it 3 ways. how much does each person pay?", answer: 120 },
  { text: "you want to save 500 dollars in 4 months. you've saved 80 dollars per month so far. how much more do you still need to save?", answer: 180 },
  { text: "a class has 30 students. 40 percent got an A. how many students got an A?", answer: 12 },
  { text: "you drive 60 miles per hour for 2 hours, then 45 miles per hour for 1 hour. how many miles did you drive in total?", answer: 165 },
  { text: "you buy 4 books at 12 dollars each and get a 25 percent discount on the total. how much do you pay?", answer: 36 },
  { text: "you and a friend split a 96-dollar grocery bill. your friend also owes you 15 dollars from last week. how much does your friend owe you in total?", answer: 63 },
]
